name: "Infra Pipeline Kuch Bhi"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  terraform-job:
    runs-on: dhondu-maharaaj
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: "32d4cf34-0003-4379-b54d-55c5630ebc59"
          tenant-id: "07b6dcc9-18d6-45a6-b3d3-7183c906e2ba"
          subscription-id: "07b6dcc9-18d6-45a6-b3d3-7183c906e2ba"    
    
